### ISSUE TITLE
Add Hoster Hosteurope Shared Hosting

### ISSUE THREAD

**Issue by kaystrobach** [mneuhaus/Famelo.Surf.SharedHosting#1]
php 5.4 path

```
/usr/bin/php5.4
```

composer have to be installed manually like @ domainfactory

**Comment by mneuhaus** [comment]
hey, just fyi, i'm not ignoring this/you, just in work-overload mode :(

**Comment by kaystrobach** [comment]
no problem, me too, otherwise i would have added a pullrequest already :smile:
